spring:
  application:
    name: user-service
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user_ms
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
      config-server: http://localhost:8888
  cloud:
    config:
      enabled: false
      bus:
        enabled: true
        kafka:
          binder:
            brokers: localhost:9092

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: DEBUG
